/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'description' : IDL.Text,
  'priority' : TaskPriority,
});
export const Volunteer = IDL.Record({
  'status' : IDL.Bool,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'completedTasks' : IDL.Nat,
  'volunteerCount' : IDL.Nat,
  'taskCount' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
  'inProgressTasks' : IDL.Nat,
  'announcementCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
  'addTask' : IDL.Func([Task], [IDL.Nat], []),
  'addVolunteer' : IDL.Func([Volunteer], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'deleteVolunteer' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'listVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'description' : IDL.Text,
    'priority' : TaskPriority,
  });
  const Volunteer = IDL.Record({
    'status' : IDL.Bool,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'completedTasks' : IDL.Nat,
    'volunteerCount' : IDL.Nat,
    'taskCount' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
    'inProgressTasks' : IDL.Nat,
    'announcementCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
    'addTask' : IDL.Func([Task], [IDL.Nat], []),
    'addVolunteer' : IDL.Func([Volunteer], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'deleteVolunteer' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'listVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };