/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'content' : string,
  'timestamp' : Time,
}
export interface DashboardStats {
  'completedTasks' : bigint,
  'volunteerCount' : bigint,
  'taskCount' : bigint,
  'pendingTasks' : bigint,
  'inProgressTasks' : bigint,
  'announcementCount' : bigint,
}
export interface Task {
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : string,
  'description' : string,
  'priority' : TaskPriority,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'status' : boolean,
  'name' : string,
  'phone' : string,
  'location' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[Announcement], bigint>,
  'addTask' : ActorMethod<[Task], bigint>,
  'addVolunteer' : ActorMethod<[Volunteer], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'deleteVolunteer' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listTasks' : ActorMethod<[], Array<Task>>,
  'listVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];